name: Codesmith-MAC-ARM
on:
  workflow_dispatch:

# Setup environment variables that will be used in the pipeline
env:
  DOCKER_FILE: dockerfile # The relative path to the dockerfile to be used. Ex: projectname/Dockerfile
  CONTAINER_NAME: deepakavanthi/codesmith # The name to be tagged to the container
  CONTAINER_REGISTRY: ghcr.io # The container registry to upload the created container
  CONTAINER_REGISTRY_USERNAME: ${{ github.actor }} # The user with appropriate rights on registry
  CONTAINER_REGISTRY_PAT: ${{ secrets.PACKAGE_ACCESS_PAT }} # The password of the user with appropriate rights on registry

jobs: 
  create-container:
    name: Build Container
    runs-on: macos-14
    steps:
      - name: Convert repository name to lowercase
        id: repository_name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.CONTAINER_REGISTRY_PAT }}

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          tags:  ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:latest
          platforms: linux/amd64
          push: true
          file: ${{ env.DOCKER_FILE }}
